# Generated by Django 5.2.4 on 2025-07-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='trackimage',
            new_name='track_image',
        ),
    ]
