# Generated by Django 5.2.4 on 2025-07-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_rename_trackimage_track_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
