# Generated by Django 5.2.4 on 2025-07-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='tags',
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='tracks/'),
        ),
    ]
