# Generated by Django 5.2.4 on 2025-08-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_remove_track_tags_alter_track_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='moderation_labels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=9),
        ),
    ]
