# Generated by Django 5.2.4 on 2025-08-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_track_moderated_at_track_moderation_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
    ]
