[tool.black]
line-length = 79
target-version = ['py39']
exclude = '''
/(
    \.eggs
  | \.git          
  | \.venv
  | _build
  | migrations
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true