# Generated by Django 5.2.4 on 2025-07-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('he/him', 'He/Him'), ('she/her', 'She/Her'), ('they/them', 'They/Them'), ("don't specify", "Don't Specify"), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
